// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface GameWindowState {
    "open": boolean;
    "mapId"?: string;
    "fullscreen": boolean;
}
