// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Active(): $CancellablePromise<boolean> {
    return $Call.ByID(953523237);
}

export function BeginPartyRound(id: string, round: number, rounds: number, deadline: number, mapStyle: string): $CancellablePromise<void> {
    return $Call.ByID(1843937144, id, round, rounds, deadline, mapStyle);
}

export function ClosePartyRound(id: string, round: number): $CancellablePromise<$models.PartyHostPlayer[] | null> {
    return $Call.ByID(1344364489, id, round);
}

export function FinishParty(id: string): $CancellablePromise<$models.PartyHostState> {
    return $Call.ByID(2374743992, id);
}

export function GetPartyHostState(id: string): $CancellablePromise<$models.PartyHostState> {
    return $Call.ByID(102006610, id);
}

export function LaunchParty(mapID: string, theme: string, accentColor: string): $CancellablePromise<$models.PartyHostState> {
    return $Call.ByID(1649410792, mapID, theme, accentColor);
}

export function LockPartyRoster(id: string): $CancellablePromise<$models.PartyHostState> {
    return $Call.ByID(4217260747, id);
}

export function PublishPartyReveal(id: string, reveal: $models.PartyRoundReveal): $CancellablePromise<void> {
    return $Call.ByID(3826933035, id, reveal);
}

export function ResetParty(id: string): $CancellablePromise<void> {
    return $Call.ByID(1953266150, id);
}

export function StopParty(id: string): $CancellablePromise<void> {
    return $Call.ByID(2166008773, id);
}
