// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface PartyHostPlayer {
    "id": string;
    "name": string;
    "color": string;
    "locked": boolean;
    "guess"?: PartyPoint | null;
    "total": number;
    "place"?: number;
}

export interface PartyHostState {
    "id": string;
    "mapId": string;
    "phase": string;
    "url": string;
    "urls": string[] | null;
    "qrCode": string;
    "rosterLocked": boolean;
    "round": number;
    "rounds": number;
    "deadline": number;
    "mapStyle": string;
    "allLocked": boolean;
    "players": PartyHostPlayer[] | null;
}

export interface PartyPlayerRound {
    "playerId": string;
    "guess"?: PartyPoint | null;
    "distanceKm"?: number | null;
    "points": number;
}

export interface PartyPoint {
    "lat": number;
    "lng": number;
}

export interface PartyRoundReveal {
    "round": number;
    "actual": PartyPoint;
    "results": PartyPlayerRound[] | null;
}
