// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function GetActiveChallenge(id: string): $CancellablePromise<string> {
    return $Call.ByID(302922630, id);
}

export function LaunchChallenge(id: string, contents: string): $CancellablePromise<void> {
    return $Call.ByID(4007215179, id, contents);
}

export function SaveChallenge(suggestedName: string, contents: string): $CancellablePromise<boolean> {
    return $Call.ByID(674236133, suggestedName, contents);
}

export function TakePendingChallenge(): $CancellablePromise<string> {
    return $Call.ByID(2442415198);
}
