// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface PluginInfo {
    "id": string;
    "name": string;
    "description": string;
    "icon": string;
    "version": string;
    "apiVersion": number;
    "main": string;
    "experimental"?: boolean;
    "settings"?: PluginSetting[] | null;
    "configured"?: string[] | null;
    "enabled": boolean;
}

export interface PluginManifest {
    "id": string;
    "name": string;
    "description": string;
    "icon": string;
    "version": string;
    "apiVersion": number;
    "main": string;
    "experimental"?: boolean;
    "settings"?: PluginSetting[] | null;
    "sha256"?: string;
}

export interface PluginModule {
    "manifest": PluginManifest;
    "source": string;
}

export interface PluginSetting {
    "key": string;
    "label": string;
    "type": string;
}
