// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Catalog(): $CancellablePromise<$models.PluginManifest[] | null> {
    return $Call.ByID(1840364293);
}

export function EnabledModules(): $CancellablePromise<$models.PluginModule[] | null> {
    return $Call.ByID(4036731676);
}

export function Install(id: string): $CancellablePromise<$models.PluginInfo> {
    return $Call.ByID(560397813, id);
}

export function Installed(): $CancellablePromise<$models.PluginInfo[] | null> {
    return $Call.ByID(1194645692);
}

export function SetEnabled(id: string, enabled: boolean): $CancellablePromise<$models.PluginInfo> {
    return $Call.ByID(1311265187, id, enabled);
}

export function SetSetting(id: string, key: string, value: string): $CancellablePromise<$models.PluginInfo> {
    return $Call.ByID(2125941506, id, key, value);
}

export function Setting(id: string, key: string): $CancellablePromise<string> {
    return $Call.ByID(2202784202, id, key);
}

export function Uninstall(id: string): $CancellablePromise<void> {
    return $Call.ByID(89046536, id);
}
